### ISSUE TITLE
感谢学长

### ISSUE THREAD

**Issue by Nighfearti** [IPreferToEatDinner/OpencvPro#1]
我直接滑跪

**Comment by IPreferToEatDinner** [comment]
加油加油，代码上面可能还是有些不太完善的地方，希望你能多提提PR，让这个项目造福下后人

**Comment by Nighfearti** [comment]
好滴😋
________________________________
发件人: 快快快去吃饭 ***@***.***>
发送时间: 2024年1月2日 16:19
收件人: IPreferToEatDinner/OpencvPro ***@***.***>
抄送: Haolin_Lee ***@***.***>; Author ***@***.***>
主题: Re: [IPreferToEatDinner/OpencvPro] 感谢学长 (Issue #1)


加油加油，代码上面可能还是有些不太完善的地方，希望你能多提提PR，让这个项目造福下后人
